### ISSUE TITLE
Add POST Characters and GET Characters

### ISSUE THREAD

**Issue by arinzingade** [arinzingade/ConvAI#28]
Create two routes: 
1. /api/createCharacters (POST) - in which admins can create a character and push them into the database in the ['characters'] collection (create characters collection seperate in mongoDB, initialize it through Flask, see line 26 of app.py, for ref.

2. /api/characters (GET) - This will simply fetch the characters present in the database and display them, on clicking it should take the user to debate room with the character.

**Comment by shubhratiwary134** [comment]
Flow for /api/charactersList:

   1. Receive GET request to fetch all characters.
   2. Retrieve characters from the characters collection.
   3. Convert ObjectIds to strings for JSON serialization.
   4. Return the list of characters.

**Comment by shubhratiwary134** [comment]
A collection for the characters in DB must be created
