### ISSUE TITLE
error in the /protected route 

### ISSUE THREAD

**Issue by shubhratiwary134** [arinzingade/ConvAI#29]
The " /protected" endpoint does not work ,when sending the request with tokens in cookies the API Gives status 401 with response message as  'Missing cookie "access_token_cookie"' ,
![Screenshot (164)](https://github.com/arinzingade/ConvAI/assets/123238414/6fa4dde0-1570-457d-89b2-21e3a1c9a820)
![Screenshot (165)](https://github.com/arinzingade/ConvAI/assets/123238414/8a60c074-6e90-4b29-a8ae-b84a388
Make sure the error handling is correct and descriptive .

**Comment by arinzingade** [comment]
Closed with Testing.
